# Generated by Django 2.2.6 on 2019-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
