# Generated by Django 2.2.7 on 2019-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0005_auto_20191130_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'item_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'review_info',
                'managed': False,
            },
        ),
    ]
