# Generated by Django 2.2.7 on 2019-11-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0006_iteminfo_reviewinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngrInfo',
            fields=[
                ('id', models.IntegerField()),
                ('ko_name', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ewg_rank', models.IntegerField(blank=True, null=True)),
                ('ko_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('eng_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skincare.Item')),
            ],
            options={
                'db_table': 'ingr_info',
                'managed': False,
            },
        ),
    ]
