# Generated by Django 2.2.6 on 2019-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20191028_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_sim',
            field=models.CharField(max_length=50),
        ),
    ]
