# Generated by Django 2.2.7 on 2019-11-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
                ('component_sim', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'information_component',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ko_name', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ewg_rank', models.IntegerField(blank=True, null=True)),
                ('ko_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('eng_desc', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'item_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'review_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ingrdesc',
        ),
        migrations.DeleteModel(
            name='IngredientsInItems',
        ),
        migrations.DeleteModel(
            name='Ingrko2Eng',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.CreateModel(
            name='IngredientsInItem',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Item')),
            ],
            options={
                'db_table': 'ingredients_in_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngrInfo',
            fields=[
                ('id', models.IntegerField()),
                ('ko_name', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ewg_rank', models.IntegerField(blank=True, null=True)),
                ('ko_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('eng_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Item')),
            ],
            options={
                'db_table': 'ingr_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsInBrand',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Item')),
            ],
            options={
                'db_table': 'items_in_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsInCategory',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Item')),
            ],
            options={
                'db_table': 'items_in_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewsInItem',
            fields=[
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Review')),
            ],
            options={
                'db_table': 'reviews_in_item',
                'managed': False,
            },
        ),
    ]
